<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\{DB,Auth};
use App\Services\{Schools,Students,Catalog,Finance,Queries,Users,Backup};
$dsn=getenv('SCHOOLLEDGER_TEST_DSN')?:'';
if(!preg_match('/dbname=([a-zA-Z0-9_]+_test)(?:;|$)/',$dsn)) { fwrite(STDERR,"Set SCHOOLLEDGER_TEST_DSN to a dedicated empty database ending in _test.\n"); exit(1); }
DB::configure(['dsn'=>$dsn,'user'=>getenv('SCHOOLLEDGER_TEST_USER')?:'root','password'=>getenv('SCHOOLLEDGER_TEST_PASSWORD')?:'']);
session_start(); $_SERVER['REMOTE_ADDR']='127.0.0.1';
$checks=[];
function ok(bool $value,string $label): void { global $checks; if(!$value) throw new RuntimeException('FAIL: '.$label); $checks[]=$label; }
function rejects(callable $fn,string $label): void { try { $fn(); } catch(DomainException|PDOException) { ok(true,$label); return; } throw new RuntimeException('FAIL: accepted '.$label); }
function latest(string $table): int { return (int)DB::one("SELECT MAX(id) id FROM $table")['id']; }
try {
    if(DB::tables()) throw new RuntimeException('Test database must be empty; this suite never clears an existing database.');
    foreach(explode(';',file_get_contents(DB::schemaFile())) as $sql) if(trim($sql)) DB::connection()->exec($sql);
    foreach(Schools::PERMISSIONS as $code) DB::insert('permissions',['code'=>$code]);
    $password='Test-only-'.bin2hex(random_bytes(12));
    DB::insert('users',['name'=>'Test super administrator','email'=>'super@example.test','password_hash'=>password_hash($password,PASSWORD_DEFAULT),'is_super'=>1]);
    ok(Auth::login('super@example.test',$password),'Super administrator login');
    $a=Schools::create(['name'=>'School A']); $_SESSION['school_id']=$a;
    $b=Schools::create(['name'=>'School B']); $_SESSION['school_id']=$a;
    ok(count(DB::all('SELECT * FROM student_types WHERE school_id=?',[$a]))===2,'Initial day and boarding categories');
    $day=(int)DB::one('SELECT id FROM student_types WHERE school_id=? AND requires_boarding=0',[$a])['id'];
    $board=(int)DB::one('SELECT id FROM student_types WHERE school_id=? AND requires_boarding=1',[$a])['id'];
    $year=date('Y'); $start=$year.'-01-01'; $end=$year.'-12-31'; $today=date('Y-m-d');
    Catalog::save(['table'=>'academic_years','name'=>$year,'starts_on'=>$start,'ends_on'=>$end]); $y=latest('academic_years');
    Catalog::save(['table'=>'terms','name'=>'Term 1','academic_year_id'=>$y,'starts_on'=>$start,'ends_on'=>$end]); $term=latest('terms');
    Catalog::save(['table'=>'classes','name'=>'Form 1']); $class=latest('classes');
    Catalog::save(['table'=>'classes','name'=>'Form 2']); $class2=latest('classes');
    Catalog::save(['table'=>'streams','name'=>'Blue','class_id'=>$class]); $stream=latest('streams');
    Catalog::save(['table'=>'streams','name'=>'Red','class_id'=>$class2]); $wrongStream=latest('streams');
    $base=['first_name'=>'Amina','last_name'=>'Moshi','gender'=>'Female','date_of_birth'=>'2012-01-02','admission_date'=>$start,'status'=>'Active','academic_year_id'=>$y,'class_id'=>$class,'stream_id'=>$stream,'starts_on'=>$start,'student_type_id'=>$day];
    $s1=Students::save(['admission_number'=>'A-001']+$base);
    $s2=Students::save(array_merge($base,['admission_number'=>'A-002','first_name'=>'Juma','student_type_id'=>$board]));
    ok(count(Queries::students()['rows'])===2,'Student registration and scoped search');
    rejects(fn()=>Students::save(array_merge($base,['admission_number'=>'BAD','stream_id'=>$wrongStream])),'Mismatched stream rejected');
    ok((int)DB::one('SELECT COUNT(*) n FROM students WHERE school_id=?',[$a])['n']===2,'Student insert rolled back on invalid enrollment');
    Catalog::save(['table'=>'fee_types','name'=>'Tuition']); $tuition=latest('fee_types');
    Catalog::save(['table'=>'fee_types','name'=>'Boarding']); $boarding=latest('fee_types');
    $structure=['academic_year_id'=>$y,'term_id'=>$term,'class_id'=>$class];
    $dayFee=Catalog::structure($structure+['student_type_id'=>$day]);
    $boardFee=Catalog::structure($structure+['student_type_id'=>$board]);
    Catalog::item(['fee_structure_id'=>$dayFee,'fee_type_id'=>$tuition,'amount'=>'1000000']);
    Catalog::item(['fee_structure_id'=>$boardFee,'fee_type_id'=>$tuition,'amount'=>'1000000']);
    Catalog::item(['fee_structure_id'=>$boardFee,'fee_type_id'=>$boarding,'amount'=>'500000']);
    $bill=['term_id'=>$term,'issued_on'=>$today,'due_on'=>$today];
    $i1=Finance::invoice($bill+['student_id'=>$s1]); $i2=Finance::invoice($bill+['student_id'=>$s2]);
    ok((int)Finance::balance($i1)['total']===100000000,'Day scholar fee structure selected');
    ok((int)Finance::balance($i2)['total']===150000000,'Boarding fee structure selected');
    rejects(fn()=>Finance::invoice($bill+['student_id'=>$s1]),'Duplicate invoice rejected');
    Catalog::item(['fee_structure_id'=>$dayFee,'fee_type_id'=>$tuition,'amount'=>'1200000']);
    ok((int)Finance::balance($i1)['total']===100000000,'Issued invoice snapshot survives fee changes');
    $pay=['invoice_id'=>$i1,'amount'=>'400000','paid_on'=>$today,'method'=>'Bank','reference'=>'BANK-1','request_key'=>bin2hex(random_bytes(24))];
    $p1=Finance::payment($pay); $balance=Finance::balance($i1);
    ok((int)$balance['paid']===40000000 && (int)$balance['balance']===60000000,'1,000,000 less 400,000 leaves 600,000');
    ok(Finance::status($balance)==='Partially Paid','Partial payment status');
    ok(Finance::payment($pay)===$p1,'Payment retry returns original payment');
    ok((int)DB::one('SELECT COUNT(*) n FROM payments')['n']===1,'Retry creates no duplicate payment');
    rejects(fn()=>Finance::payment(array_merge($pay,['amount'=>'1'])),'Request key cannot be reused with a different amount');
    rejects(fn()=>Finance::payment(array_merge($pay,['request_key'=>bin2hex(random_bytes(24)),'amount'=>'700000','reference'=>'BANK-2'])),'Overpayment rejected');
    rejects(fn()=>Finance::payment(array_merge($pay,['request_key'=>bin2hex(random_bytes(24))])),'Duplicate bank reference rejected');
    ok((int)DB::one('SELECT balance_after FROM receipts WHERE payment_id=?',[$p1])['balance_after']===60000000,'Receipt captures balance after posting');
    Finance::adjust(['invoice_id'=>$i1,'kind'=>'Discount','amount'=>'100000','reason'=>'Approved scholarship']);
    ok((int)Finance::balance($i1)['balance']===50000000,'Discount reduces actual balance');
    rejects(fn()=>Finance::adjust(['invoice_id'=>$i1,'kind'=>'Credit','amount'=>'600000','reason'=>'Too much']),'Excess credit rejected');
    rejects(fn()=>Finance::cancel(['invoice_id'=>$i1,'reason'=>'Test']),'Cannot cancel paid invoice');
    Finance::reverse(['payment_id'=>$p1,'reason'=>'Incorrect bank entry']);
    ok((int)Finance::balance($i1)['balance']===90000000,'Reversal restores invoice balance');
    rejects(fn()=>Finance::reverse(['payment_id'=>$p1,'reason'=>'Again']),'Duplicate reversal rejected');
    $p2=Finance::payment(array_merge($pay,['amount'=>'900000','reference'=>'BANK-CORRECT','request_key'=>bin2hex(random_bytes(24))]));
    ok(Finance::status(Finance::balance($i1))==='Paid','Full settlement status');
    $statement=Queries::statement($s1); ok(end($statement)['balance']===0,'Statement reconciles charge, discount, reversal and settlement');
    Catalog::save(['table'=>'hostels','name'=>'East']); $hostel=latest('hostels'); Catalog::save(['table'=>'rooms','name'=>'Room 1','hostel_id'=>$hostel]); $room=latest('rooms'); Catalog::save(['table'=>'beds','name'=>'Bed 1','room_id'=>$room]); $bed=latest('beds');
    rejects(fn()=>Students::board(['student_id'=>$s1,'bed_id'=>$bed,'starts_on'=>$today]),'Day scholar boarding assignment rejected');
    Students::board(['student_id'=>$s2,'bed_id'=>$bed,'starts_on'=>$today,'meals'=>'Full board']);
    $s3=Students::save(array_merge($base,['admission_number'=>'A-003','first_name'=>'Neema','student_type_id'=>$board]));
    rejects(fn()=>Students::board(['student_id'=>$s3,'bed_id'=>$bed,'starts_on'=>$today]),'Double bed occupancy rejected');
    DB::transaction(fn()=>Students::enroll($s1,array_merge($base,['class_id'=>$class2,'stream_id'=>'','starts_on'=>$today])));
    ok((int)DB::one('SELECT COUNT(*) n FROM student_academic_history WHERE student_id=?',[$s1])['n']===2,'Promotion preserves enrollment history');
    ok((int)Finance::balance($i1)['total']===90000000,'Promotion does not change historical invoice');
    rejects(fn()=>Finance::invoice($bill+['student_id'=>$s1]),'Missing matching fee structure rejected');
    $_SESSION['school_id']=$b;
    rejects(fn()=>Auth::owned('students',$s1),'Application blocks foreign student');
    rejects(fn()=>Finance::payment($pay),'Application blocks foreign invoice payment');
    ok(count(Queries::students()['rows'])===0 && count(Queries::invoices())===0,'Queries isolate school B');
    rejects(fn()=>DB::insert('fee_structure_items',['school_id'=>$b,'fee_structure_id'=>$dayFee,'fee_type_id'=>$tuition,'amount'=>100]),'Composite foreign key blocks cross-school relationship');
    $_SESSION['school_id']=$a;
    $role=(int)DB::one("SELECT id FROM roles WHERE school_id=? AND name='Teacher'",[$a])['id'];
    Users::save(['name'=>'Teacher','email'=>'teacher@example.test','password'=>$password,'role_id'=>$role]);
    $studentRole=(int)DB::one("SELECT id FROM roles WHERE school_id=? AND name='Student'",[$a])['id'];
    Users::save(['name'=>'Student','email'=>'student@example.test','password'=>$password,'role_id'=>$studentRole,'student_id'=>$s1]);
    $accountantRole=(int)DB::one("SELECT id FROM roles WHERE school_id=? AND name='Accountant / Bursar'",[$a])['id'];
    Users::save(['name'=>'Accountant','email'=>'accountant@example.test','password'=>$password,'role_id'=>$accountantRole]);
    $backup=Backup::create(); $data=json_decode(gzdecode(file_get_contents(ROOT.'/storage/'.$backup)),true);
    ok((int)$data['school']['id']===$a && count($data['tables']['students'])===3,'Backup contains selected school');
    ok(count(array_filter($data['tables']['users'],fn($u)=>(int)$u['school_id']!==$a))===0,'Backup excludes foreign/global users');
    ok(Auth::login('teacher@example.test',$password),'Teacher login'); $_SESSION['school_id']=$b;
    ok(Auth::schoolId()===$a,'Tenant user cannot switch school through session selector');
    rejects(fn()=>Finance::invoice($bill+['student_id'=>$s2]),'Teacher denied invoice write');
    rejects(fn()=>Queries::statement($s1),'Teacher denied student financial statement');
    rejects(fn()=>Users::save(['name'=>'Unauthorized']),'Teacher denied user management');
    ok(Auth::login('student@example.test',$password),'Student login');
    ok(count(Queries::statement($s1))>0,'Student can view own statement');
    rejects(fn()=>Queries::statement($s2),'Student cannot view another student statement');
    ok(Auth::login('accountant@example.test',$password),'Accountant login');
    rejects(fn()=>Finance::reverse(['payment_id'=>$p2,'reason'=>'Unauthorized']),'Accountant denied reversal without permission');
    ok(!Auth::can('users.manage') && Auth::can('payments.write'),'Accountant permission matrix');
    ok(Auth::login('super@example.test',$password),'Return to super administrator'); $_SESSION['school_id']=$a;
    Finance::cancel(['invoice_id'=>$i2,'reason'=>'Withdrawn before payment']);
    ok(Finance::status(Finance::balance($i2))==='Cancelled','Cancellation state retained');
    $statement2=Queries::statement($s2); ok(end($statement2)['balance']===0,'Cancelled invoice statement reconciles');
    ok((int)DB::one('SELECT COUNT(*) n FROM notification_outbox WHERE school_id=?',[$a])['n']===4,'Financial outbox events committed');
    ok((int)DB::one("SELECT COUNT(*) n FROM audit_logs WHERE action='payment.recorded'")['n']===2,'Only committed payments audited');
    $bad='locked@example.test'; for($i=0;$i<6;$i++) ok(!Auth::login($bad,'incorrect'),'Invalid login attempt '.($i+1));
    ok((int)DB::one('SELECT MAX(failures) n FROM login_attempts')['n']===5,'Login rate limit stops attempts at five');
    file_put_contents(ROOT.'/tests/.runtime-fixture.json',json_encode(['dsn'=>$dsn,'password'=>$password,'school'=>$a,'student'=>$s1,'invoice'=>$i1,'payment'=>$p2,'backup'=>$backup]));
    echo 'PASS: '.count($checks)." integration checks\n".implode("\n",array_map(fn($c)=>'  ✓ '.$c,$checks))."\n";
} catch(Throwable $e) { fwrite(STDERR,$e."\n"); exit(1); }
