<?php $daily=\App\Services\DailyBackup::status(); global $config; ?>
<section class="panel narrow"><h2>Automatic daily database backup</h2>
<p>Status: <strong><?= ($config['automatic_database_backup']??true)?'Enabled':'Disabled' ?></strong></p>
<p>The system creates a full database backup on the first signed-in visit each day. Backups are stored privately on the application server.</p>
<?php if(!empty($config['backup_storage_ephemeral'])): ?><p class="note">This hosting uses temporary storage. Backup files can be lost after a restart or deployment. Durable backup storage has not been connected yet.</p><?php endif ?>
<?php if($daily): ?><p>Last successful backup: <strong><?= e($daily['completed_at']) ?></strong></p><?php else: ?><p class="note">No successful database backup has been recorded yet.</p><?php endif ?>
<?php if(($config['automatic_database_backup']??true) && substr($daily['completed_at']??'',0,10)!==date('Y-m-d')): ?><p class="note">Today's backup is pending or failed. Ask the server administrator to check the backup logs and database dump utility.</p><?php endif ?>
<p class="note">For backups on days without visitors, schedule <code>php bin/backup-database.php</code> on the hosting server. Keep another copy in durable offsite storage.</p></section>
<section class="panel narrow"><span class="stat-icon green">↧</span><h2>Keep a protected copy.</h2><p>Create a compressed backup of this school’s records, role permissions and uploaded images. The file is stored outside the public directory and downloaded to your computer.</p><p class="note">This backup contains sensitive student records and password hashes. Store it in an encrypted location with restricted access. Tenant recovery uses the administrator CLI.</p><?php startForm('backup.create',[],'stack'); endForm('Create & download school backup'); ?></section>
